// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_aspnetcore_iroxit.DAL;

namespace api_aspnetcore_iroxit.DAL.Migrations
{
    [DbContext(typeof(IroxitContext))]
    [Migration("20190720063045_Correcion5Mig")]
    partial class Correcion5Mig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("api_aspnetcore_iroxit.Entities.Productos", b =>
                {
                    b.Property<int>("IDProductos")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<int>("Existencias");

                    b.Property<decimal>("PrecioUnitario");

                    b.Property<string>("Titulo")
                        .HasMaxLength(200);

                    b.HasKey("IDProductos");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("api_aspnetcore_iroxit.Entities.Ventas", b =>
                {
                    b.Property<int>("IDVentas")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantidadVendida");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("IDProductos");

                    b.HasKey("IDVentas");

                    b.HasIndex("IDProductos");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("api_aspnetcore_iroxit.Entities.Ventas", b =>
                {
                    b.HasOne("api_aspnetcore_iroxit.Entities.Productos", "Producto")
                        .WithMany()
                        .HasForeignKey("IDProductos")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
